config/routes.rb
Rails.application.routes.draw do
  #get 'profiles/show'
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #:resources posts
  root 'posts#index'
  get ':user_name',  to: 'profiles#show', as: :profile
  get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
  patch ':user_name/edit', to: 'profiles#update', as: :update_profile

  resources :posts do   
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    validates :user_id, presence: true
    validates :caption, presence: true, length: { minimum: 3, maximum: 300 }
    belongs_to :user
    has_many :comments, dependent: :destroy
    validates :image, presence: true
    has_attached_file :image, styles: { :medium=> "640x" }

    validates_attachment_content_type :image, :content_type =>
    /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_attached_file :avatar, styles: { medium: '152x162#' }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_post

    def index 
        @comments = @post.comments.order("created_at ASC")
            respond_to do |format|
            format.html { render layout: !request.xhr? }
        end
    end
    
    def create
        @comment = @post.comments.build(comment_params)
        @comment.user_id = current_user.id
        if @comment.save
            respond_to do |format|
                format.html { redirect_to root_path }
                format.js
            end
        else
            flash[:alert] = "Failed to create post. Check the form"
            render root_path
        end
    end

    def destroy
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        respond_to do |format|
            format.html { redirect_to root_path }
            format.js
        end
    end

    private

    def comment_params
        params.require(:comment).permit(:context)
    end
    
    def set_post
        @post = Post.find(params[:post_id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :owned_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all.order('created_at DESC').page params[:page]
  end

  def show
  end

  def new
    #@post = Post.new
    #add devise configurations
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    #if @post = Post.create(post_params)
    if @post.save
      flash[:success] = "Your post has been created"
      redirect_to posts_path
    else
      flash.now[:alert] = "Your new post couldn't be created! Please check the form"
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post updated."
      redirect_to posts_path
    else
      flash.now[:alert] = "Update failed. Please check the form"
      render :edit
    end
  end
  
  def delete
    
  end

  def destroy
    @post.destroy
    flash[:success] = "Post deleted."
    redirect_to posts_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:image, :caption)
  end

  def owned_post
    
    unless current_user == @post.user
      flash[:alert] = "That post doesn't belong to you!"
      redirect_to root_path
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user
  before_action :owned_profile, only: [:edit, :update]
  before_action :authenticate_user!


  def show
    @posts = User.find_by(user_name: params[:user_name]).posts.order('created_at DESC')
  end

  def edit
  end
  
  def update
    if @user.update(profile_params)
      flash[:success] = 'Your profile has been updated.'
      redirect_to profile_path(@user.user_name)
    else
      @user.errors.full_messages
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end

  private

  def set_user
    @user = User.find_by(user_name: params[:user_name])
  end

  def profile_params
    params.require(:user).permit(:avatar, :bio)
  end

  def owned_profile
    unless current_user == @user
      flash[:alert] = "That profile doesn't belong to you!"
      redirect_to root_path
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private
  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password,
    :password_confirmation)
  end
  def account_update_params
    params.require(:user).permit(:email, :user_name, :password,
    :password_confirmation, :current_password)
  end
 end
 

app/helpers/application_helper.rb
module ApplicationHelper
def alert_for(flash_type)
    { success: 'alert-success',
    error: 'alert-danger',
    alert: 'alert-warning',
    notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
    end

    def form_image_select(post)
        return image_tag post.image.url(:medium),
        id: 'image-preview',
        class: 'img-responsive' if post.image.exists?
        image_tag 'placeholder.jpg', id: 'image-preview', class: 'img-responsive'
    end

    def profile_avatar_select(user)
        return image_tag user.avatar.url(:medium),
                         id: 'image-preview',
                         class: 'img-responsive img-circle profile-image' if user.avatar.exists?
        image_tag 'default-avatar.jpg', id: 'image-preview',
                                        class: 'img-responsive img-circle profile-image'
      end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/comments/_comment.html.erb
<div id="comment">
  <div class="user-name">
    <%= link_to comment.user.user_name, profile_path(comment.user.user_name) %>
  </div>
  <div class="comment-content">
    <%= comment.context %>
  </div>
  
  <% if comment.user == current_user %>
    <%= link_to post_comment_path(post, comment), method: :delete, data: {post_id: post.id, value: post.comments.count, confirm: "Are you sure?" }, remote: true, id: "delete-#{comment.id}", class: "delete-comment" do %>
      <span class="glyphicon glyphicon-remove delete-comment-icon"></span>
    <% end %>
  <% end %>
</div>

app/views/comments/create.js.erb
$('#comment_content_<%= @post.id %>').val('')
$('#comment_content_<%= @post.id %>').blur();
Append.comment_count += 1
$(Append.id).attr('data-value', Append.comment_count);
if (Append.comment || Append.open ){ $('#comments_<%= @post.id
%>').append("<%=j render 'comments/comment', post: @post, comment:
@comment %>"); }
else if ((Append.comment && Append.open) === false && Append.link ===
true) {
$('#comments_' + Append.post_id).append("<div class='paginator'
id='#comments-paginator-" + Append.post_id + "'><a class='more-
comments' id='more_comments_" + Append.post_id + "' data-post-id='" +
Append.post_id + "' data-type='html' data-remote='true' data-value='"
+ Append.comment_count + "' href='/posts/" + Append.post_id +
"/comments'>view all " + Append.comment_count + " comments</a>
</div>");
ClickableCommentsLink();
}
else if ((Append.comment && Append.open && Append.link) === false) {
$('#more_comments_<%= @post.id %>').html("view all <%=
@post.comments.count %> comments"); }

app/views/comments/destroy.js.erb
$('#comments_<%= @post.id %>').html("<%= j render @post.comments, post: @post, comment: @comment %>");
Append.comment_count -= 1

app/views/comments/index.html.erb
<%= render @comments, post: @post%>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="navbar-container"></div>
  <div class="navbar-header"></div>
  <button class="navbar-toggle collapsed" data-target="#bs-navbar-collapse-1" data-toggle="collapse" type="button"></button>
  <span class="sr-only">Toggle Navigation</span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <div class="navbar-brand">
    <%= link_to "Instabook", root_path %>
  </div>
  <br>

  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
      <% end %>
  </div>
  
  <div class="collapse navbar-collapse" id="#bs-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <% if (user_signed_in?) %>
        <li>
        <%= link_to "New Post", new_post_path %>
         <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        </li>
      <% else %>
        <li>
         <%= link_to "Login", new_user_session_path %>
        </li>
        <li>
         <%= link_to "Register", new_user_registration_path %>
       </li>
     <% end %>  
    </ul>
   </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instabook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="posts-wrapper">
    <div class="post">
        <div class="post-body">
            <div class="image-wrap">

                <%= form_image_select(@post) %>
                <%= simple_form_for @post, html: {multipart: true } do |f| %>
                <div class="row">
                    <div class="col-md-12 text-cemter">
                        <%= f.error_notification%>
                    </div>
                </div>
                <div class="container-fluid">
                    <div class="form-group text-center">
                        <h4>Upload an image (this is required):</h4>
                        <%= f.input :image, label: false, input_html: {
                            onChange: 'loadFile(event)'}
                        %>
                    </div>
                    <div class="form-group text-center">
                        <%= f.input :caption, label: false, placeholder: 'Add your caption'%>
                    </div>
                    <div class="form-group text-center">
                        <%= f.button :submit, class: 'btn-success btn-block'%>
                    </div>
                </div>
                <%end%>
            </div>
        </div>
    </div>
</div>

app/views/posts/_post.html.erb
<div class="posts-wrapper row" style="border: 10px solid rgb(100, 100, 100);">
  
  <div class="user-name col-lg-6">
    <%= link_to post.user.user_name, profile_path(post.user.user_name) %>
  </div>
  <div class="time-ago col-lg-6">
    <%= time_ago_in_words post.created_at%>
  </div>
  
  <div class="image center-block">
    <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>

    <div class="post-botton">
      <div class="caption">
        <div class="user-name">
          <%= post.caption %>
        </div>
        
        <!---<div class="comments" id="comments_<%= post.id %>">
          <%# if post.comments %>
              <% #= render post.comments, post: post %>
          <% #end %>
          </div>
        -->

          <div class="comments" id="comments_<%= post.id %>">
            <% if post.comments.any? %>
              <%= render post.comments.first(4), post: post %>
              <% unless post.comments.count <= 4 %>
                <div class="paginator" id="#comments-paginator-<%= post.id %>">
                  <%= link_to "view all #{post.comments.count} comments", post_comments_path(post), remote: true, class: 'more-comments', id: "more_comments_#{post.id}", data:{post_id: "#{post.id}", type: "html", value: "#{post.comments.count}"} %>
                </div>
              <% end %>
            <% end %>
          </div>


          <div class="comment-like-form row">
            <div class="like-button col-sm-1">
                <span class="glyphicon glyphicon-heart-empty"></span>
            </div>
            <div class="comment-form">
                <div class="col-sm-11 ">
                    <%= form_for [post, post.comments.build], remote: true do |f| %>                    
                    <%= f.text_field :context , placeholder: 'Add a comment...', class: "comment_content", id: "comment_content_#{post.id}"%>
                    <%= f.submit %>
                <%end%>
                </div>
            </div>

            <br>
        </div>
      </div>
    </div>    

  </div>
  </div>

</div>

app/views/posts/_posts.html.erb
<% @posts.each do |post| %>
    <%=render 'post', post: post%>
<%end%>

app/views/posts/edit.html.erb
<div class="form-wrapper row">



<%= render 'form'%>

<div class="text-center edit-links">
    <%= link_to "Delete Post", post_path(@post), method: :delete, data:{
        confirm: "Are you sure you want to delete this post?" }%>
        |
        <%= link_to "cancel", posts_path%>
</div>
</div>

app/views/posts/index.html.erb
<div id="posts">
  <%= render 'posts' %>
</div>
<div class="text-center" id="paginator">
  <%= link_to_next_page @posts, 'LOAD MORE', remote: true, id: 'load_more' %>
</div>

app/views/posts/index.js.erb
$('#posts').append("<%= escape_javascript(render 'posts')%>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@posts,
'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator').remove(); }

app/views/posts/new.html.erb
<div class="form-wrapper row">

<%= render 'form'%>
</div>

app/views/posts/show.html.erb
<%= render 'post', post: @post%>

<% if @post.user.id == current_user.id %>
  <div class="text-center edit-links">
    <%= link_to "Cancel", posts_path %>
    |
    <%= link_to "Edit Post", edit_post_path(@post) %>
  </div>
<% else %>
  <div class="text-center edit-links">
    <%= link_to "Cancel", posts_path %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-body">
      <div class="image-wrap">
        <%= form_for @user, url: {action: "update"}, html: { multipart: true } do |f| %>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group text-center">
                <h4>Change your profile image:</h4>
                <div class="img-circle">
                  <%= profile_avatar_select(@user) %>
                </div>
                <%= f.file_field :avatar, onChange: 'loadFile(event)' %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group text-center">
                <h4>Update your bio:</h4>
                <%= f.text_area :bio, label: false, rows: 4 %>
              </div>
            </div>
          </div>
          <div class="form-group text-center">
            <%= f.submit "Update Profile", class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="posts-wrapper">
  <div class="row profile-header">
    <div class="col-md-6">
      <div class="img-circle">
        <%= profile_avatar_select(@user) %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="user-name-and-follow">
        <h3 class="profile-user-name">
          <%= @user.user_name %>
        </h3>
        <span>
          <% if @user == current_user %>
            <%= link_to 'Edit Profile', edit_profile_path(@user.user_name),
              class: 'btn edit-button' %>
            <% end %>
          
        </span>
      </div>
      <p class="profile-bio">
        <%= @user.bio %>
      </p>
      <div class="user-statistics">
        <p>
          <%= pluralize @user.posts.count, 'post' %>
        </p>
      </div>
    </div>
  </div>
</div>

<% @posts.each do |post| %>
    <%= render 'posts/post', post: post%>
<%end%>